version: '3.7'

services:
    cli_php:
        build:
            context: ./
            dockerfile: Dockerfile
        container_name: cli_php_json_api_blackfire
        env_file: 'blackfire.io.env'
        volumes:
            - ./../:/app:ro
        working_dir: /app/perf/
        stop_grace_period: 1s
        command: >
            sh -c "
                mkdir -p /var/log/php && \
                touch /var/log/php/error.log && \
                tail -f /var/log/php/error.log
            "
