name: Code_Checks

on: [push, pull_request]

jobs:
    tests:
        runs-on: ubuntu-20.04
        strategy:
            matrix:
                php:
                    - '7.4'
                    - '8.0'
                    - '8.1'

        name: PHP ${{ matrix.php }} / Ubuntu
        steps:
            -   uses: actions/checkout@v2

            -   uses: shivammathur/setup-php@v2
                with:
                    php-version: ${{ matrix.php }}
                    coverage: none # disable xdebug, pcov

            -   name: Get Composer Cache Directory
                id: composer-cache
                run: |
                    echo "::set-output name=dir::$(composer config cache-files-dir)"

            -   uses: actions/cache@v3
                with:
                    path: ${{ steps.composer-cache.outputs.dir }}
                    key: php-${{ matrix.php }}-composer-${{ hashFiles('**/composer.lock') }}
                    restore-keys: |
                        php-${{ matrix.php }}-composer-

            -   run: composer install -a --no-interaction --no-progress --prefer-dist

            -   uses: actions/cache@v3
                if: ${{ matrix.php == '8.1' }}
                with:
                    path: .php-cs-fixer.cache
                    key: php-cs-fixer-cache

            -   run: composer test-cs-fixer
                if: ${{ matrix.php == '8.1' }}

            -   uses: actions/cache@v3
                if: ${{ matrix.php == '8.1' }}
                with:
                    path: /tmp/phpstan
                    key: phpstan-cache

            -   run: composer phpstan:check
                if: ${{ matrix.php == '8.1' }}

            -   run: vendor/bin/phpunit
